#!/usr/bin/env bash

# Run MySQL-specific db unit test suites

function showHelp {
echo "usage: unittest dir"
echo "       Where dir is the same as a sites/dir directive in your yaml configuration"
}

if [ "$1" == "" ]; then
  showHelp
  exit 1
fi
if [ "$1" == "--help" ]; then
showHelp
echo ""
echo ""
exit 0
fi

#determine which path we're running from and where composer is located
UPATH="web"
if [ ! -f "../$UPATH" ]; then
  UPATH="../.."
fi

export HABITAT=true;

SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CPATH="$SCRIPT_PATH/composer"

INCPATH="`php -i | grep include_path | awk 'BEGIN{ FS=" => " }{ printf($NF) }'`:$CPATH"

cd ../$UPATH/$1

php -d include_path=${INCPATH} "$SCRIPT_PATH/composer/vendor/bin/phpunit" -c testFramework/dbtests/phpunit.xml
